package cat.xtec.merli.duc.client.services;

import java.util.List;
import com.google.gwt.user.client.rpc.AsyncCallback;

import cat.xtec.merli.domain.lom.Resource;
import cat.xtec.merli.domain.taxa.Category;
import cat.xtec.merli.domain.taxa.Entity;
import cat.xtec.merli.domain.taxa.Term;
import cat.xtec.merli.domain.taxa.Vertex;


/**
 * Autogenerated asynchronous client RPC service interface.
 * @see cat.xtec.merli.duc.client.services.DucService
 */
public interface DucServiceAsync {
    void fetchCategory(String id, String iri, AsyncCallback<Category> callback);
    void fetchEntity(String id, String iri, AsyncCallback<Entity> callback);
    void fetchResource(String id, String iri, AsyncCallback<Resource> callback);
    void fetchTerm(String id, String iri, AsyncCallback<Term> callback);
    void fetchChildren(String id, String iri, AsyncCallback<List<Vertex>> callback);
    void removeEntity(String id, String iri, AsyncCallback<Void> callback);
}
